name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up python
    - name: Sets up Python 3.10.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.16

    - name: Install dependendencies
      run: |
        make install

    - name: Lint with pylint
      run: |
        make lint

    - name: Format code
      run: |
        make format